manager_node:
  ros__parameters:
    rate:
      state_machine: 0.3

    waypoints:
      qty_points: 9
      points: [2.0, 0.0, 1.5,
               2.0, 2.0, 1.5,
               0.0, 2.0, 1.5,
               0.0, 0.0, 1.5,
               0.0, 0.0, 4.0,
               2.0, 0.0, 4.0,
               2.0, 2.0, 4.0,
               0.0, 2.0, 4.0,
               0.0, 0.0, 4.0]
